# GitHub FUNDING.yml
# Supported funding platforms configuration

github: brazilianscriptguy
patreon: brazilianscriptguy

custom:
  - https://www.buymeacoffee.com/brazilianscriptguy
  - https://ko-fi.com/brazilianscriptguy
  - https://www.gofundme.com/f/brazilianscriptguy
