name: changelog-releases-and-nuget-publisher

on:
  workflow_dispatch:
  release:
    types: [published]
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  cleanup-old-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq gh

      - name: Configure GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh auth setup-git

      - name: Delete Older Releases for Managed Tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          MANAGED_TAGS=("BlueTeam-Tools" "Core-ScriptLibrary" "ITSM-Templates-SVR" "ITSM-Templates-WKS" "SysAdmin-Tools" "GPOs-Templates" "READMEs-Files-Package" "All-Repository-Files" "AD-SSO-APIs-Integration")
          for tag in "${MANAGED_TAGS[@]}"; do
            releases=$(gh release list --tag "$tag" --limit 100 --json name,tagName,createdAt | jq -r --arg tag "$tag" '.[] | select(.tagName == $tag) | "\(.createdAt) \(.tagName)"')
            if [ -z "$releases" ]; then continue; fi
            sorted_releases=$(echo "$releases" | sort)
            releases_to_delete=$(echo "$sorted_releases" | head -n -1 | awk '{print $2}')
            for old_tag in $releases_to_delete; do
              gh release delete "$old_tag" -y
              git push --delete origin "$old_tag"
            done
          done

  build-and-release:
    needs: cleanup-old-releases
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release_name: [
          "BlueTeam-Tools",
          "Core-ScriptLibrary",
          "ITSM-Templates-SVR",
          "ITSM-Templates-WKS",
          "SysAdmin-Tools",
          "GPOs-Templates",
          "READMEs-Files-Package",
          "All-Repository-Files",
          "AD-SSO-APIs-Integration"
        ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip jq gh
          pwsh -Command "Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser"

      - name: Build, Analyze, and Package
        env:
          RELEASE_NAME: ${{ matrix.release_name }}
        run: |
          mkdir -p artifacts lint-reports temp

          case "$RELEASE_NAME" in
            BlueTeam-Tools)
              cp -r BlueTeam-Tools/* temp/
              ;;
            Core-ScriptLibrary)
              cp -r Core-ScriptLibrary/* temp/
              ;;
            ITSM-Templates-WKS)
              cp -r ITSM-Templates-WKS/* temp/
              ;;
            ITSM-Templates-SVR)
              cp -r ITSM-Templates-SVR/* temp/
              ;;
            SysAdmin-Tools)
              cp -r SysAdmin-Tools/* temp/
              ;;
            GPOs-Templates)
              cp -r SysAdmin-Tools/GroupPolicyObjects-Templates/* temp/
              ;;
            AD-SSO-APIs-Integration)
              cp -r SysAdmin-Tools/ActiveDirectory-SSO-Integrations/* temp/
              ;;
            READMEs-Files-Package)
              cp README.md temp/main-README.md || true
              find . -type f -iname "README.md" ! -path "./README.md" | while read -r f; do
                cp "$f" "temp/$(basename "$(dirname "$f")")-README.md"
              done
              ;;
            All-Repository-Files)
              cp -r BlueTeam-Tools/* temp/
              cp -r Core-ScriptLibrary/* temp/
              cp -r ITSM-Templates-SVR/* temp/
              cp -r ITSM-Templates-WKS/* temp/
              cp -r SysAdmin-Tools/* temp/
              cp README.md temp/ || true
              ;;
          esac

          pwsh -Command "Get-ChildItem -Recurse -Path temp -Include *.ps1 | Invoke-ScriptAnalyzer -Recurse -Severity Warning,Error | Out-File 'lint-reports/$RELEASE_NAME-AnalyzerReport.txt' -Encoding utf8"

          ZIP_NAME="Suite-$RELEASE_NAME.zip"
          pushd temp > /dev/null
          zip -r "../artifacts/$ZIP_NAME" .
          popd > /dev/null

          sha256sum "artifacts/$ZIP_NAME" > "artifacts/$ZIP_NAME.sha256"
          rm -rf temp

      - name: Extract Release Notes
        id: extract_notes
        run: |
          tag="${{ matrix.release_name }}"
          body=$(awk -v tag="## $tag" '$0 == tag {found=1; next} /^## / && found {exit} found {print}' CHANGELOG.md)
          echo "release_body<<EOF" >> $GITHUB_ENV
          echo "${body:-No release notes found.}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ matrix.release_name }}
          name: ${{ matrix.release_name }}
          body: ${{ env.release_body }}
          files: |
            artifacts/ProSuite-${{ matrix.release_name }}.zip
            artifacts/ProSuite-${{ matrix.release_name }}.zip.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact Zip and SHA256 for NuGet Job
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.release_name }}
          path: |
            artifacts/ProSuite-${{ matrix.release_name }}.zip
            artifacts/ProSuite-${{ matrix.release_name }}.zip.sha256

      - name: Upload Lint Report
        uses: actions/upload-artifact@v4
        with:
          name: PSScriptAnalyzer-${{ matrix.release_name }}
          path: lint-reports/${{ matrix.release_name }}-AnalyzerReport.txt

  build-and-publish-nuget:
    needs: build-and-release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release_name: [
          "BlueTeam-Tools",
          "Core-ScriptLibrary",
          "ITSM-Templates-SVR",
          "ITSM-Templates-WKS",
          "SysAdmin-Tools"
        ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install PowerShell and .NET
        run: |
          sudo apt-get update
          sudo apt-get install -y powershell
          pwsh -Command "Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser"
        shell: bash

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts-${{ matrix.release_name }}
          path: ./artifacts

      - name: Generate .nuspec
        shell: pwsh
        run: |
          $version = "${{ github.run_number }}.0.0"
          $releaseNotesPath = "CHANGELOG.md"
          ./Core-ScriptLibrary/Nuget-Package-Publisher/nuspec-generator.ps1 `
            -PackageId "${{ matrix.release_name }}" `
            -Version $version `
            -ZipPath "./artifacts/ProSuite-${{ matrix.release_name }}.zip" `
            -ReleaseNotesPath $releaseNotesPath `
            -OutputPath "."

      - name: Pack NuGet Package
        run: |
          dotnet nuget pack "${{ matrix.release_name }}.nuspec" --output ./nupkg

      - name: Push to GitHub Packages
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --name github --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
          dotnet nuget push "nupkg/${{ matrix.release_name }}.*.nupkg" --source github --api-key ${{ secrets.GITHUB_TOKEN }}
