name: make-github-releases

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC

permissions:
  contents: write

jobs:
  cleanup-github-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq gh

      - name: Delete Older Releases for Managed Tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          MANAGED_TAGS=("AD-SSO-APIs-Integration" "All-Repository-Files" "BlueTeam-Tools" "Core-ScriptLibrary" "GPOs-Templates" "ITSM-Templates-SVR" "ITSM-Templates-WKS" "READMEs-Files-Package" "SysAdmin-Tools")
          for tag in "${MANAGED_TAGS[@]}"; do
            releases=$(gh release list --limit 100 --json name,tagName,createdAt | jq -r --arg tag "$tag" '.[] | select(.tagName | startswith($tag)) | "\(.createdAt) \(.tagName)"')
            if [ -z "$releases" ]; then continue; fi
            sorted_releases=$(echo "$releases" | sort)
            releases_to_delete=$(echo "$sorted_releases" | head -n -1 | awk '{print $2}')
            for old_tag in $releases_to_delete; do
              gh release delete "$old_tag" -y || true
              git push --delete origin "$old_tag" || true
            done
          done

  update-github-releases:
    needs: cleanup-github-releases
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release_name: [
          "AD-SSO-APIs-Integration",
          "All-Repository-Files",
          "BlueTeam-Tools",
          "Core-ScriptLibrary",
          "GPOs-Templates",
          "ITSM-Templates-SVR",
          "ITSM-Templates-WKS",
          "READMEs-Files-Package",
          "SysAdmin-Tools"
        ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip jq gh

      - name: Generate Version Tag
        id: version_tag
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          DATE_TAG=$(date +'%Y%m%d')
          VERSION_TAG="${{ matrix.release_name }}-${DATE_TAG}-${COMMIT_HASH}"
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV

      - name: Package Release: ${{ matrix.release_name }}
        run: |
          set -e
          mkdir -p artifacts

          case "${{ matrix.release_name }}" in
            BlueTeam-Tools | Core-ScriptLibrary | ITSM-Templates-SVR | ITSM-Templates-WKS | SysAdmin-Tools)
              cp -r "${{ matrix.release_name }}" "temp-${{ matrix.release_name }}"
              cp README.md "temp-${{ matrix.release_name }}/" || true
              cp LICENSE "temp-${{ matrix.release_name }}/" || true
              zip -r "artifacts/${{ matrix.release_name }}.zip" "temp-${{ matrix.release_name }}"
              rm -rf "temp-${{ matrix.release_name }}"
              ;;
            GPOs-Templates)
              mkdir -p GPOs-Templates
              cp -r SysAdmin-Tools/GroupPolicyObjects-Templates/* GPOs-Templates/ || true
              cp SysAdmin-Tools/ActiveDirectory-Management/Export-n-Import-GPOsTool.ps1 GPOs-Templates/ || true
              cp README.md LICENSE GPOs-Templates/ || true
              zip -r artifacts/GPOs-Templates.zip GPOs-Templates
              rm -rf GPOs-Templates
              ;;
            READMEs-Files-Package)
              mkdir -p READMEs-Files-Package
              cp README.md READMEs-Files-Package/main-README.md || true
              find . -type f -iname "README.md" ! -path "./README.md" | while read -r file; do
                repo_dir=$(dirname "$file")
                repo_name=$(basename "$repo_dir")
                cp "$file" "READMEs-Files-Package/${repo_name}-README.md"
              done
              zip -r artifacts/READMEs-Files-Package.zip READMEs-Files-Package
              rm -rf READMEs-Files-Package
              ;;
            All-Repository-Files)
              if [ -d "All-Repository-Files" ]; then
                zip -r artifacts/All-Repository-Files.zip All-Repository-Files
              else
                mkdir -p All-Repository-Files
                for dir in BlueTeam-Tools Core-ScriptLibrary ITSM-Templates-SVR ITSM-Templates-WKS SysAdmin-Tools; do
                  cp -r "$dir" All-Repository-Files/ || true
                done
                cp README.md LICENSE All-Repository-Files/ || true
                zip -r artifacts/All-Repository-Files.zip All-Repository-Files
                rm -rf All-Repository-Files
              fi
              ;;
            AD-SSO-APIs-Integration)
              mkdir -p AD-SSO-APIs-Integration
              cp -r SysAdmin-Tools/ActiveDirectory-SSO-Integrations/* AD-SSO-APIs-Integration/ || true
              zip -r artifacts/AD-SSO-APIs-Integration.zip AD-SSO-APIs-Integration
              rm -rf AD-SSO-APIs-Integration
              ;;
          esac

      - name: Generate SHA256 Checksum
        run: sha256sum "artifacts/${{ matrix.release_name }}.zip" > "artifacts/${{ matrix.release_name }}.sha256.txt"

      - name: Extract Release Notes from CHANGELOG.md
        id: extract_notes
        run: |
          tag="## ${{ matrix.release_name }}"
          body=$(awk -v tag="$tag" '
            $0 == tag {found=1; next}
            /^## / && found {exit}
            found {print}
          ' CHANGELOG.md)
          echo "release_body<<EOF" >> $GITHUB_ENV
          echo "${body:-No changelog available.}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1.1.0
        with:
          tag_name: ${{ env.VERSION_TAG }}
          release_name: ${{ env.VERSION_TAG }}
          body: ${{ env.release_body }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Main Artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/${{ matrix.release_name }}.zip
          asset_name: ${{ matrix.release_name }}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SHA256 File
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/${{ matrix.release_name }}.sha256.txt
          asset_name: ${{ matrix.release_name }}.sha256.txt
          asset_content_type: text/plain
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact Archive to GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.release_name }}
          path: artifacts/${{ matrix.release_name }}.zip
