name: Publish NuGet Package

on:
  push:
    branches: [main]
  release:
    types: [published, prerelease]

permissions:
  contents: write
  packages: write

jobs:
  publish-nuget:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: 🛠️ Debug workflow start
        run: |
          echo "Workflow started for ITSMAndSysAdminTools"
          echo "Event: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Commit: ${{ github.sha }}"
          ls -R
          echo "Verifying critical files:"
          ls -l ITSMAndSysAdminTools.nuspec || echo "❌ Missing .nuspec"
          ls -l README.md LICENSE icon.png CHANGELOG.md || echo "⚠️ One or more root files are missing"

      - name: 📦 Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mono-complete xmlstarlet
          wget -O nuget.exe https://dist.nuget.org/win-x86-commandline/v6.11.0/nuget.exe
          chmod +x nuget.exe
          sudo mv nuget.exe /usr/local/bin/nuget
          mono --version
          xmlstarlet --version
          mono /usr/local/bin/nuget help | head -n 1

      - name: 📁 Prepare and stage files
        id: prepare
        run: |
          pkg="ITSMAndSysAdminTools"
          nuspec="ITSMAndSysAdminTools.nuspec"
          mkdir -p ReadmeCopies nupkg-out "tmp-$pkg"
          for dir in Core-ScriptLibrary BlueTeam-Tools SysAdmin-Tools ITSM-Templates-WKS ITSM-Templates-SVR; do
            [ -d "$dir" ] && cp -r "$dir/." "tmp-$pkg/$dir/" || echo "⚠️ Folder $dir not found"
          done
          cp "$nuspec" "tmp-$pkg/$nuspec" || { echo "❌ Failed to copy $nuspec"; echo "skip=true" >> "$GITHUB_OUTPUT"; exit 0; }
          cp README.md "tmp-$pkg/$pkg-README.md" || cp Core-ScriptLibrary/README.md "tmp-$pkg/$pkg-README.md" || echo "⚠️ README not found"
          cp icon.png "tmp-$pkg/icon.png" || cp Core-ScriptLibrary/icon.png "tmp-$pkg/icon.png" || echo "⚠️ icon.png not found"
          cp LICENSE "tmp-$pkg/LICENSE" || cp Core-ScriptLibrary/LICENSE "tmp-$pkg/LICENSE" || {
            echo "❌ LICENSE file missing"; echo "skip=true" >> "$GITHUB_OUTPUT"; exit 0;
          }
          xmlstarlet val "$nuspec" || { echo "❌ Invalid XML in $nuspec"; echo "skip=true" >> "$GITHUB_OUTPUT"; exit 0; }

      - name: 🧠 Enrich Nuspec Metadata
        if: steps.prepare.outputs.skip != 'true'
        id: enrich
        run: |
          pkg="ITSMAndSysAdminTools"
          nuspec="tmp-$pkg/$pkg.nuspec"
          version=$(xmlstarlet sel -t -m "//metadata/version" -v . "$nuspec")
          echo "version=$version" >> "$GITHUB_OUTPUT"

          changelog=$(awk "/^## \\[$version\\]/,/^## \\[/" CHANGELOG.md | sed '1d;/^## \\[/d' || echo "No changelog found for version $version")
          [ -z "$changelog" ] && changelog="No changelog found for version $version"

          artifact_url="https://github.com/${{ github.repository }}/packages"
          browse_url="https://github.com/${{ github.repository }}/tree/${{ github.ref_name }}"
          download_links="\n\n📦 Download .nupkg: $artifact_url\n📁 Browse files: $browse_url"
          full_notes="$changelog$download_links"

          full_notes_escaped=$(echo "$full_notes" | sed \
            -e 's/&/\&/g' \
            -e 's/</\</g' \
            -e 's/>/\>/g' \
            -e 's/"/\"/g' \
            -e "s/'/\'/g")

          echo "$full_notes_escaped" | iconv -t UTF-8 > enriched_release_notes.txt
          echo "notes=$full_notes_escaped" >> "$GITHUB_OUTPUT"

          if [ ! -f enriched_release_notes.txt ]; then
            echo "❌ enriched_release_notes.txt not found"
            exit 1
          fi

          notes=$(cat enriched_release_notes.txt)

          echo "Current .nuspec content:"
          cat "$nuspec"

          xmlstarlet ed -L \
            -u "//metadata/releaseNotes" -v "$notes" \
            -u "//metadata/tags" -v "powershell itsm sysadmin security gpo automation enterprise activedirectory network wsus configuration sso ldap" \
            -u "//metadata/iconUrl" -v "icon.png" \
            -s "//metadata[not(repository)]" -t elem -n "repository" -v "" \
            -i "//metadata/repository" -t attr -n "type" -v "git" \
            -i "//metadata/repository" -t attr -n "url" -v "https://github.com/${{ github.repository }}" \
            -i "//metadata/repository" -t attr -n "branch" -v "${{ github.ref_name }}" \
            -i "//metadata/repository" -t attr -n "commit" -v "${{ github.sha }}" \
            "$nuspec" || { echo "❌ xmlstarlet failed to update $nuspec"; exit 1; }

          echo "Updated .nuspec content:"
          cat "$nuspec"

      - name: 📦 Pack NuGet package
        if: steps.prepare.outputs.skip != 'true'
        run: |
          cd "tmp-ITSMAndSysAdminTools"
          mono /usr/local/bin/nuget pack ITSMAndSysAdminTools.nuspec \
            -OutputDirectory ../nupkg-out \
            -Symbols -SymbolPackageFormat snupkg -NonInteractive

      - name: 🚀 Push to GitHub Packages
        if: steps.prepare.outputs.skip != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for pkg in nupkg-out/*.nupkg nupkg-out/*.snupkg; do
            [ -f "$pkg" ] && mono /usr/local/bin/nuget push "$pkg" \
              -Source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
              -ApiKey "$GITHUB_TOKEN" -NonInteractive -SkipDuplicate || echo "⚠️ No packages found or push skipped"
          done

      - name: 🚀 Push to NuGet.org
        if: steps.prepare.outputs.skip != 'true'
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          for pkg in nupkg-out/*.nupkg nupkg-out/*.snupkg; do
            [ -f "$pkg" ] && mono /usr/local/bin/nuget push "$pkg" \
              -Source "https://api.nuget.org/v3/index.json" \
              -ApiKey "$NUGET_API_KEY" -NonInteractive -SkipDuplicate || echo "⚠️ No packages found or push skipped"
          done

      - name: 🏷️ Create Git tag
        if: steps.prepare.outputs.skip != 'true'
        run: |
          tag="ITSMAndSysAdminTools-v${{ steps.enrich.outputs.version }}"
          if ! git tag --list | grep -q "^$tag$"; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git tag "$tag"
            git push origin "$tag"
          fi

      - name: 🧹 Clean up
        if: always()
        run: |
          rm -rf tmp-ITSMAndSysAdminTools ReadmeCopies nupkg-out enriched_release_notes.txt || true
          
