name: Publish NuGet Package

on:
  push:
    branches: [main]
  release:
    types: [published, prerelease]

permissions:
  contents: write
  packages: write

jobs:
  publish-nuget:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: 🛠️ Debug workflow start
        run: |
          echo "Workflow started for package ITSMAndSysAdminTools"
          echo "Event: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Commit: ${{ github.sha }}"
          echo "Listing repository contents:"
          ls -R

      - name: 📦 Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mono-complete
          wget -O nuget.exe https://dist.nuget.org/win-x86-commandline/v6.11.0/nuget.exe
          chmod +x nuget.exe
          sudo mv nuget.exe /usr/local/bin/nuget

      - name: 📁 Prepare and stage files
        run: |
          pkg="ITSMAndSysAdminTools"
          nuspec="$pkg.nuspec"
          mkdir -p nupkg-out "tmp-$pkg"

          for dir in BlueTeam-Tools Core-ScriptLibrary ITSM-Templates-SVR ITSM-Templates-WKS SysAdmin-Tools; do
            if [ -d "$dir" ]; then
              cp -r "$dir/." "tmp-$pkg/$dir/"
            fi
          done

          cp "$nuspec" "tmp-$pkg/$pkg.nuspec"
          cp README.md "tmp-$pkg/$pkg-README.md" || true
          cp icon.png "tmp-$pkg/icon.png" || true
          cp LICENSE "tmp-$pkg/LICENSE.txt"

      - name: 📦 Pack NuGet package
        run: |
          pkg="ITSMAndSysAdminTools"
          cd "tmp-$pkg"
          mono /usr/local/bin/nuget pack "$pkg.nuspec" \
            -OutputDirectory ../nupkg-out \
            -Symbols -SymbolPackageFormat snupkg \
            -NonInteractive

      - name: 🚀 Push to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for pkg_path in nupkg-out/*.nupkg nupkg-out/*.snupkg; do
            [ -f "$pkg_path" ] && mono /usr/local/bin/nuget push "$pkg_path" \
              -Source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
              -ApiKey "$GITHUB_TOKEN" -NonInteractive -SkipDuplicate
          done

      - name: 🏷️ Create Git tag
        run: |
          version=$(xmlstarlet sel -t -m "//metadata/version" -v . "tmp-ITSMAndSysAdminTools/ITSMAndSysAdminTools.nuspec")
          tag="ITSMAndSysAdminTools-v$version"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "$tag"
          git push origin "$tag"

      - name: 🧹 Clean up
        if: always()
        run: |
          rm -rf "tmp-ITSMAndSysAdminTools" nupkg-out || true
