name: 📝 Auto-Generate CHANGELOG.md by Toolset

on:
  push:
    branches: [main]
    paths-ignore:
      - CHANGELOG.md

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to get full git history

      - name: Generate toolset-based changelog
        run: |
          echo "# Changelog" > CHANGELOG.md

          for dir in SysAdmin-Tools BlueTeam-Tools Core-ScriptLibrary \
                     ITSM-Templates-WKS ITSM-Templates-SVR \
                     GPOs-Templates AD-SSO-APIs-Integration; do
            echo -e "\n## $dir" >> CHANGELOG.md
            git log --pretty=format:"- %s" -- "$dir" | head -n 50 >> CHANGELOG.md
          done

      - name: Commit and push updated CHANGELOG.md
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add CHANGELOG.md
          git commit -m "docs: auto-update CHANGELOG.md by toolset [skip ci]" || echo "No changes"
          git push
